### ISSUE TITLE
Memory leak in grad-cam implementation

### ISSUE THREAD

**Issue by pshwetank** [kazuto1011/grad-cam-pytorch#36]
Hi @kazuto1011 ,
I would like to highlight that there is potentially a memory leak in the grad-cam implementation. When I run the code on GPU over a large batch, it does not purge the batch even after backward pass and GPU memory keeps piling up. The code runs fine if I just want to get visualisations on few no of images but the sample size is large, I often end up getting CUDA: out of memory error. 
Currently, I am also trying to resolve this bug but if you can take notice, please try to figure it out yourself as well since you are the original creater of the repo. It will be easier for you to find out the issue.

**Comment by AhmedFrikha** [comment]
Hi @pshwetank, I am currently having the same problem. Did you manage to resolve it ? Thanks.

**Comment by daniegr** [comment]
@pshwetank: I am experiencing a similar issue on CPU. Any progress here?

**Comment by pshwetank** [comment]
Hi @AhmedFrikha , 
Yeah....I actually fixed it by deleting the base wrapper after every batch and running the purge command for gpu memory. It works now without any memory leaks and I can take as many gradcam images as I want. I will try to commit the code soon for your help.

**Comment by aliechoes** [comment]
hey @pshwetank I also faced the same problem. Did you commit the code? appreciated!

**Comment by ahmedhshahin** [comment]
@aliechoes @AhmedFrikha after every batch, and assuming `gc` is your model wrapper, try to do the following:
```
del gcam
# if using cpu
import gc
gc.collect()
# if gpu
torch.cuda.empty_cache()
```
